Day 7: Some Assembly Required ---
This year, Santa brought little Bobby Tables a set of wires and bitwise logic gates! Unfortunately, little Bobby is a little under the recommended age range, and he needs help assembling the circuit.

Each wire has an identifier (some lowercase letters) and can carry a 16-bit signal (a number from 0 to 65535). A signal is provided to each wire by a gate, another wire, or some specific value. Each wire can only get a signal from one source, but can provide its signal to multiple destinations. A gate provides no signal until all of its inputs have a signal.

The included instructions booklet describes how to connect the parts together: x AND y -> z means to connect wires x and y to an AND gate, and then connect its output to wire z.

For example:

123 -> x means that the signal 123 is provided to wire x.
x AND y -> z means that the bitwise AND of wire x and wire y is provided to wire z.
p LSHIFT 2 -> q means that the value from wire p is left-shifted by 2 and then provided to wire q.
NOT e -> f means that the bitwise complement of the value from wire e is provided to wire f.
Other possible gates include OR (bitwise OR) and RSHIFT (right-shift). If, for some reason, you'd like to emulate the circuit instead, almost all programming languages (for example, C, JavaScript, or Python) provide operators for these gates.

For example, here is a simple circuit:

123 -> x

456 -> y

x AND y -> d

x OR y -> e

x LSHIFT 2 -> f

y RSHIFT 2 -> g

NOT x -> h

NOT y -> i

After it is run, these are the signals on the wires:

d: 72

e: 507

f: 492

g: 114

h: 65412

i: 65079

x: 123

y: 456

In little Bobby's kit's instructions booklet (provided as your puzzle input), what signal is ultimately provided to wire a?

In [1]:
import numpy as np
logic = []
for i in range(0,16):
    logic.append(2**i)
print(logic)
logic =sorted(logic, reverse=True)
print(logic)

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768]
[32768, 16384, 8192, 4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8, 4, 2, 1]


In [2]:
def bitwise(number):
    if type(number)==int:
        size=16
        number_bit=np.zeros((size),dtype=np.int16)
        i=0
        for item in logic:
            if number >= item:
                number -=item      
                number_bit[i]=1
                i +=1
            else:
                i+=1
        return((number_bit))
x=bitwise(123)
y=bitwise(456)
print(x)
print(y)

[0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1]
[0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 0]


In [3]:
def bit16():
    size=16
    num=np.zeros((size),dtype=np.int16)
    return num
def one():
    num=bit16()
    num[15]=1
    return num
    

In [4]:
x= one()
print(x)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


In [5]:
def num_and (num1, num2):
    size = 16
    new_num = np.zeros((size),dtype=np.int16)
    for i in range(0,size):
        if (num1[i]==1) and (num2[i]==1):
            new_num[i]=1
    return new_num

def num_or (num1, num2):
    size=16
    new_num=np.zeros((size),dtype=np.int16)
    for i in range(0,size):
        if num1[i]==1 or num2[i]==1:
            new_num[i]=1
    return new_num 

def num_not (num):
    size=16
    new_num=np.zeros((size),dtype=np.int16)
    for i in range(0,size):
        if num[i]==0:
            new_num[i]=1
    return new_num 

In [6]:
def r_shift(num,shift):
    size=16
    new_num=np.zeros((size),dtype=np.int16)
    for i in range(shift,size-shift):
        new_num[i+shift]=num[i]
    return new_num

def l_shift(num, shift):
    size=16
    new_num=np.zeros((size),dtype=np.int16)
    for i in range(shift,size):
        new_num[i-shift]=num[i]
    return new_num
        

In [7]:
with open(r"C:\Users\myavu\OneDrive\Desktop\Questions\2015\7.txt") as f:
    lines =f. read().splitlines()
for line in lines:
    ff=line.split(' ')
    print(ff)

['lf', 'AND', 'lq', '->', 'ls']
['iu', 'RSHIFT', '1', '->', 'jn']
['bo', 'OR', 'bu', '->', 'bv']
['gj', 'RSHIFT', '1', '->', 'hc']
['et', 'RSHIFT', '2', '->', 'eu']
['bv', 'AND', 'bx', '->', 'by']
['is', 'OR', 'it', '->', 'iu']
['b', 'OR', 'n', '->', 'o']
['gf', 'OR', 'ge', '->', 'gg']
['NOT', 'kt', '->', 'ku']
['ea', 'AND', 'eb', '->', 'ed']
['kl', 'OR', 'kr', '->', 'ks']
['hi', 'AND', 'hk', '->', 'hl']
['au', 'AND', 'av', '->', 'ax']
['lf', 'RSHIFT', '2', '->', 'lg']
['dd', 'RSHIFT', '3', '->', 'df']
['eu', 'AND', 'fa', '->', 'fc']
['df', 'AND', 'dg', '->', 'di']
['ip', 'LSHIFT', '15', '->', 'it']
['NOT', 'el', '->', 'em']
['et', 'OR', 'fe', '->', 'ff']
['fj', 'LSHIFT', '15', '->', 'fn']
['t', 'OR', 's', '->', 'u']
['ly', 'OR', 'lz', '->', 'ma']
['ko', 'AND', 'kq', '->', 'kr']
['NOT', 'fx', '->', 'fy']
['et', 'RSHIFT', '1', '->', 'fm']
['eu', 'OR', 'fa', '->', 'fb']
['dd', 'RSHIFT', '2', '->', 'de']
['NOT', 'go', '->', 'gp']
['kb', 'AND', 'kd', '->', 'ke']
['hg', 'OR', 'hh', '->', 'h

In [8]:
def parsing(line):
    command_table= ["0", "0", "0", "0"]
    line= line.split(" ")
    if len(line)== 3:
        #mylist[line[2]]=line[0]
        command_table[0]="bitwise"
        command_table[1]=line[0]
        command_table[2]=line[2]            
    elif len(line)==4:
        #mylist[line[3]]=0
        command_table[0]=line[0]
        command_table[1]=line[1]
        command_table[2]=line[3]
    elif len(line)==5:
        #mylist[line[4]]=0
        command_table[0]=line[1]
        command_table[1]=line[0]
        command_table[2]=line[2]
        command_table[3]=line[4]
    return command_table 

In [9]:
for line in lines:
    command=parsing (line)
    print(command)


['AND', 'lf', 'lq', 'ls']
['RSHIFT', 'iu', '1', 'jn']
['OR', 'bo', 'bu', 'bv']
['RSHIFT', 'gj', '1', 'hc']
['RSHIFT', 'et', '2', 'eu']
['AND', 'bv', 'bx', 'by']
['OR', 'is', 'it', 'iu']
['OR', 'b', 'n', 'o']
['OR', 'gf', 'ge', 'gg']
['NOT', 'kt', 'ku', '0']
['AND', 'ea', 'eb', 'ed']
['OR', 'kl', 'kr', 'ks']
['AND', 'hi', 'hk', 'hl']
['AND', 'au', 'av', 'ax']
['RSHIFT', 'lf', '2', 'lg']
['RSHIFT', 'dd', '3', 'df']
['AND', 'eu', 'fa', 'fc']
['AND', 'df', 'dg', 'di']
['LSHIFT', 'ip', '15', 'it']
['NOT', 'el', 'em', '0']
['OR', 'et', 'fe', 'ff']
['LSHIFT', 'fj', '15', 'fn']
['OR', 't', 's', 'u']
['OR', 'ly', 'lz', 'ma']
['AND', 'ko', 'kq', 'kr']
['NOT', 'fx', 'fy', '0']
['RSHIFT', 'et', '1', 'fm']
['OR', 'eu', 'fa', 'fb']
['RSHIFT', 'dd', '2', 'de']
['NOT', 'go', 'gp', '0']
['AND', 'kb', 'kd', 'ke']
['OR', 'hg', 'hh', 'hi']
['LSHIFT', 'jm', '1', 'kg']
['NOT', 'cn', 'co', '0']
['RSHIFT', 'jp', '2', 'jq']
['RSHIFT', 'jp', '5', 'js']
['AND', '1', 'io', 'ip']
['LSHIFT', 'eo', '15', 'es']
['AND

In [10]:
lines_count=0
for line in lines:
    lines_count+=1
    command=parsing (line)
print(lines_count)

339


In [11]:
def find_firstnumbers(lines):
    my_dict={}
    for line in lines:        
        command=parsing(line)
        if command[0]=="bitwise":
            try:         
                my_dict[command[2]]=bitwise(int(command[1]))
            except:                              
                my_dict[command[1]]=bit16()
                my_dict[command[2]]=bit16()
        elif command[0]=="AND":
            if command[1]=='1':
                my_dict[command[1]]=one()
                my_dict[command[3]]=bit16()
            else:           
                my_dict[command[3]]=bit16()
        elif command[0]=="OR":
            my_dict[command[3]]=bit16()
        elif command[0]=="NOT":
            my_dict[command[2]]=bit16()
        elif command[0]=="LSHIFT":
            my_dict[command[3]]=bit16()
        elif command[0]=="RSHIFT":
            my_dict[command[3]]=bit16()
        elif command[0]=="LSHIFT":
            my_dict[command[2]]=bit16()
    #print(my_dict['ge'])
        
    return my_dict

In [12]:
#find_firstnumbers(lines)

In [13]:
def find_numbers(lines):
    new_dict=find_firstnumbers(lines)
    for i in range(lines_count):
        for line in lines:
            command=parsing(line)
            if command[0]=="AND":
                new_dict[command[3]]=num_and(new_dict[command[1]], new_dict[command[2]])
            elif command[0]=="OR":
                new_dict[command[3]]=num_or(new_dict[command[1]], new_dict[command[2]])
            elif command[0]=="LSHIFT":
                new_dict[command[3]]=l_shift(new_dict[command[1]], int(command[2]))
            elif command[0]=="RSHIFT":
                new_dict[command[3]]=r_shift(new_dict[command[1]], int(command[2]))
            elif command[0]=="NOT":
                new_dict[command[2]]=num_not(new_dict[command[1]])
    return new_dict

In [14]:
numbers= find_numbers(lines)
find_numbers(lines)

{'ls': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16),
 'jn': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int16),
 'bv': array([0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1], dtype=int16),
 'hc': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0], dtype=int16),
 'eu': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1], dtype=int16),
 'by': array([0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1], dtype=int16),
 'iu': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int16),
 'o': array([0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0], dtype=int16),
 'gg': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1], dtype=int16),
 'ku': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16),
 'ed': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int16),
 'ks': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16),
 'hl': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int16),


In [15]:
def converter(numbers):
    values=numbers.copy()
    for key, value in dict.items(numbers):
        val=0
        number =np.flip(value) 
        for i in range(0,16):
            val += (2**i) * number[i]
        values[key]=val    
    return values

In [16]:
converter(numbers)

{'ls': 0,
 'jn': 2,
 'bv': 887,
 'hc': 18,
 'eu': 37,
 'by': 887,
 'iu': 4,
 'o': 19454,
 'gg': 125,
 'ku': 65535,
 'ed': 1,
 'ks': 0,
 'hl': 2,
 'ax': 20,
 'lg': 0,
 'df': 74,
 'fc': 4,
 'di': 2,
 'it': 0,
 'em': 65501,
 'ff': 32951,
 'fn': 0,
 'u': 0,
 'ma': 0,
 'kr': 0,
 'fy': 65533,
 'fm': 74,
 'fb': 55,
 'de': 149,
 'gp': 65535,
 'ke': 32770,
 'hi': 2,
 'kg': 4018,
 'co': 65530,
 'jq': 0,
 'js': 0,
 '1': 1,
 'ip': 0,
 'es': 32768,
 'jk': 1,
 'j': 334,
 'ck': 149,
 'gq': 5,
 'fv': 11,
 'lm': 0,
 'jo': 32768,
 'iw': 0,
 'ij': 65535,
 'cd': 1,
 'bp': 299,
 'gx': 65531,
 'fu': 65535,
 'jp': 32770,
 'jc': 1,
 'hw': 502,
 'b': 19138,
 'gm': 1,
 'ht': 32788,
 'er': 149,
 'ap': 0,
 'lf': 32768,
 'ce': 2,
 'cc': 35375,
 'bm': 32768,
 'io': 10,
 'ai': 2527,
 'bl': 2392,
 'lh': 0,
 'et': 32917,
 'ay': 65515,
 'db': 598,
 'fg': 17,
 'ln': 0,
 'n': 1022,
 'ia': 2,
 'lb': 8036,
 'ez': 65535,
 'dj': 65533,
 'eg': 110,
 'lx': 16074,
 'a': 0,
 'ja': 65535,
 'hd': 32768,
 'cf': 3,
 'ft': 0,
 'bb': 

In [17]:
numbers['a']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)