Day 7: Some Assembly Required ---
This year, Santa brought little Bobby Tables a set of wires and bitwise logic gates! Unfortunately, little Bobby is a little under the recommended age range, and he needs help assembling the circuit.

Each wire has an identifier (some lowercase letters) and can carry a 16-bit signal (a number from 0 to 65535). A signal is provided to each wire by a gate, another wire, or some specific value. Each wire can only get a signal from one source, but can provide its signal to multiple destinations. A gate provides no signal until all of its inputs have a signal.

The included instructions booklet describes how to connect the parts together: x AND y -> z means to connect wires x and y to an AND gate, and then connect its output to wire z.

For example:

123 -> x means that the signal 123 is provided to wire x.
x AND y -> z means that the bitwise AND of wire x and wire y is provided to wire z.
p LSHIFT 2 -> q means that the value from wire p is left-shifted by 2 and then provided to wire q.
NOT e -> f means that the bitwise complement of the value from wire e is provided to wire f.
Other possible gates include OR (bitwise OR) and RSHIFT (right-shift). If, for some reason, you'd like to emulate the circuit instead, almost all programming languages (for example, C, JavaScript, or Python) provide operators for these gates.

For example, here is a simple circuit:

123 -> x

456 -> y

x AND y -> d

x OR y -> e

x LSHIFT 2 -> f

y RSHIFT 2 -> g

NOT x -> h

NOT y -> i

After it is run, these are the signals on the wires:

d: 72

e: 507

f: 492

g: 114

h: 65412

i: 65079

x: 123

y: 456

In little Bobby's kit's instructions booklet (provided as your puzzle input), what signal is ultimately provided to wire a?

In [1]:
import numpy as np
logic = []
for i in range(0,16):
    logic.append(2**i)
print(logic)
logic =sorted(logic, reverse=True)
print(logic)

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768]
[32768, 16384, 8192, 4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8, 4, 2, 1]


In [2]:
def bitwise(number):
    if type(number)==int:
        size=16
        number_bit=np.zeros((size),dtype=np.int16)
        i=0
        for item in logic:
            if number >= item:
                number -=item      
                number_bit[i]=1
                i +=1
            else:
                i+=1
        return((number_bit))
x=bitwise(123)
y=bitwise(456)
print(x)
print(y)

[0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1]
[0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 0]


In [3]:
def bit16():
    size=16
    num=np.zeros((size),dtype=np.int16)
    return num
def one():
    num=bit16()
    num[15]=1
    return num
    

In [4]:
x= one()
print(x)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


In [5]:
def num_and (num1, num2):
    size = 16
    new_num = np.zeros((size),dtype=np.int16)
    for i in range(0,size):
        if (num1[i]==1) and (num2[i]==1):
            new_num[i]=1
    return new_num

def num_or (num1, num2):
    size=16
    new_num=np.zeros((size),dtype=np.int16)
    for i in range(0,size):
        if num1[i]==1 or num2[i]==1:
            new_num[i]=1
    return new_num 

def num_not (num):
    size=16
    new_num=np.zeros((size),dtype=np.int16)
    for i in range(0,size):
        if num[i]==0:
            new_num[i]=1
    return new_num 

In [6]:
def r_shift(num,shift):
    size=16
    new_num=np.zeros((size),dtype=np.int16)
    for i in range(shift,size-shift):
        new_num[i+shift]=num[i]
    return new_num

def l_shift(num, shift):
    size=16
    new_num=np.zeros((size),dtype=np.int16)
    for i in range(shift,size):
        new_num[i-shift]=num[i]
    return new_num
        

In [7]:
with open(r"C:\Users\myavu\OneDrive\Desktop\Questions\2015\7a.txt") as f:
    lines =f. read().splitlines()
for line in lines:
    ff=line.split(' ')
    print(ff)

['x', 'AND', 'y', '->', 'd']
['x', 'OR', 'y', '->', 'e']
['456', '->', 'y']
['x', 'LSHIFT', '2', '->', 'f']
['y', 'RSHIFT', '2', '->', 'g']
['NOT', 'x', '->', 'h']
['NOT', 'y', '->', 'i']
['123', '->', 'x']


In [8]:
def parsing(line):
    command_table= ["0", "0", "0", "0"]
    line= line.split(" ")
    if len(line)== 3:
        #mylist[line[2]]=line[0]
        command_table[0]="bitwise"
        command_table[1]=line[0]
        command_table[2]=line[2]            
    elif len(line)==4:
        #mylist[line[3]]=0
        command_table[0]=line[0]
        command_table[1]=line[1]
        command_table[2]=line[3]
    elif len(line)==5:
        #mylist[line[4]]=0
        command_table[0]=line[1]
        command_table[1]=line[0]
        command_table[2]=line[2]
        command_table[3]=line[4]
    return command_table 

In [9]:
for line in lines:
    command=parsing (line)
    print(command)


['AND', 'x', 'y', 'd']
['OR', 'x', 'y', 'e']
['bitwise', '456', 'y', '0']
['LSHIFT', 'x', '2', 'f']
['RSHIFT', 'y', '2', 'g']
['NOT', 'x', 'h', '0']
['NOT', 'y', 'i', '0']
['bitwise', '123', 'x', '0']


In [10]:
lines_count=0
for line in lines:
    lines_count+=1
    command=parsing (line)
print(lines_count)

8


In [11]:
def find_firstnumbers(lines):
    my_dict={}
    for line in lines:        
        command=parsing(line)
        if command[0]=="bitwise":
            try:         
                my_dict[command[2]]=bitwise(int(command[1]))
            except:                              
                my_dict[command[1]]=bit16()
                my_dict[command[2]]=bit16()
        elif command[0]=="AND":
            if command[1]=='1':
                my_dict[command[1]]=one()
                my_dict[command[3]]=bit16()
            else:           
                my_dict[command[3]]=bit16()
        elif command[0]=="OR":
            my_dict[command[3]]=bit16()
        elif command[0]=="NOT":
            my_dict[command[2]]=bit16()
        elif command[0]=="LSHIFT":
            my_dict[command[3]]=bit16()
        elif command[0]=="RSHIFT":
            my_dict[command[3]]=bit16()
        elif command[0]=="LSHIFT":
            my_dict[command[2]]=bit16()
    #print(my_dict['ge'])
        
    return my_dict

In [12]:
#find_firstnumbers(lines)

In [13]:
def find_numbers(lines):
    new_dict=find_firstnumbers(lines)
    for i in range(lines_count):
        for line in lines:
            command=parsing(line)
            if command[0]=="AND":
                new_dict[command[3]]=num_and(new_dict[command[1]], new_dict[command[2]])
            elif command[0]=="OR":
                new_dict[command[3]]=num_or(new_dict[command[1]], new_dict[command[2]])
            elif command[0]=="LSHIFT":
                new_dict[command[3]]=l_shift(new_dict[command[1]], int(command[2]))
            elif command[0]=="RSHIFT":
                new_dict[command[3]]=r_shift(new_dict[command[1]], int(command[2]))
            elif command[0]=="NOT":
                new_dict[command[2]]=num_not(new_dict[command[1]])
    return new_dict

In [14]:
numbers= find_numbers(lines)
find_numbers(lines)

{'d': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0], dtype=int16),
 'e': array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int16),
 'y': array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0], dtype=int16),
 'f': array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0], dtype=int16),
 'g': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0], dtype=int16),
 'h': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0], dtype=int16),
 'i': array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1], dtype=int16),
 'x': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1], dtype=int16)}

In [15]:
def converter(numbers):
    values=numbers.copy()
    for key, value in dict.items(numbers):
        val=0
        number =np.flip(value) 
        for i in range(0,16):
            val += (2**i) * number[i]
        values[key]=val    
    return values

In [16]:
converter(numbers)

{'d': 72,
 'e': 507,
 'y': 456,
 'f': 492,
 'g': 114,
 'h': 65412,
 'i': 65079,
 'x': 123}